### ISSUE TITLE
gcc-v验证下载时报错

### ISSUE THREAD

**Issue by C0coYu** [FloatingShuYin/development-environment-manual#2]
gcc : 无法将“gcc”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，
然后再试一次。
所在位置 行:1 字符: 1
+ gcc -v
+ ~~~
    + CategoryInfo          : ObjectNotFound: (gcc:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by I-Want-ToBelieve** [comment]
应该是 gcc 没有成功下载并安装
卸载重新装下:
```powershell
sudo scoop uninstall gcc -g
sudo scoop install gcc -g
```
